# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          buildConfiguration: 'Release'
        
        steps:
        - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'dotnet build $(buildConfiguration)'

  - stage: Deploy
    jobs:
      - job: Deploy
        pool:
          vmImage: 'vs2017-win2016'
        steps:
          - 
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            appType: 'webApp'
            WebAppName: 'roshapp'
            packageForLinux: '$(System.ArtifactsDirectory)/drop/*.zip'
            